services:
  mongo:
    image: mongo:8.2
    container_name: movie_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: movie_backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cinemax
      - NODE_ENV=development
      - JWT_SECRET=supersecret123

    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://movie_backend:5001
    depends_on:
      - backend
    volumes: 
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data: